### ISSUE TITLE
ValueError: Audio file is not long enough

### ISSUE THREAD

**Issue by borishanzju** [p-lambda/jukemir#11]
restore jukebox/models/5b/prior_level_2.pth.tar
Restored from jukebox/models/5b/prior_level_2.pth.tar
  0%|                                                                                                                                                                              | 0/60 [00:35<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 177, in <module>
    representation = get_acts_from_file(input_path, hps, vqvae, top_prior, meanpool=True)
  File "main.py", line 86, in get_acts_from_file
    z = get_z(audio, vqvae)
  File "main.py", line 32, in get_z
    raise ValueError('Audio file is not long enough')
ValueError: Audio file is not long enough

**Comment by rodrigo-castellon** [comment]
Sorry for the late response. You can see exactly why this gets raised (https://github.com/p-lambda/jukemir/blob/96d67b9af0d62f39ac0cd656d09ea63a08a13b31/representations/jukebox/main.py#L31). The API asks for audio of at least ~24 seconds.

**Comment by borishanzju** [comment]
How can I adopt the repo to short audio

**Comment by rodrigo-castellon** [comment]
I'd recommend taking a look at the [colab notebook](https://colab.research.google.com/drive/1x4qt_-SLrSSRzOuz7dkuxTK-o4fSoH9n?usp=sharing). The notebook code supports this capability.
