### ISSUE TITLE
Precomputed features link broken

### ISSUE THREAD

**Issue by nmagal** [p-lambda/jukemir#13]
Hi,

The link for the pre-computed features gives a 404 error code. Is there anyway we can get this link working?

Thanks!

**Comment by dberat** [comment]
Hello,

Did you find a way to access the pre-computed features? I am looking for those but no chance so far. 

Thank you

**Comment by nmagal** [comment]
I was unable to access the given link. But their docker image worked.

**Comment by dberat** [comment]
Thank you for your answer. Were you able to access the features by running the Docker image? I am trying that but it does not work for me.
