### ISSUE TITLE
Dockerfile incomplete?

### ISSUE THREAD

**Issue by rfalcon100** [p-lambda/jukemir#3]
Hi,

I am interested in extracting jukebox representations with my own dataset. I've looked at the readme where you provide a Docker environment and instructions and how to process data. However, I am running in a server cluster where Docker containers are not well supported.

I was thinking of replicating the environment by looking at the source [DockerFile](https://github.com/p-lambda/jukemir/blob/main/docker/Dockerfile), but it seems to be different than the command list in the [docker image](https://hub.docker.com/repository/docker/jukemir/representations_jukebox). Ideally I would like to create a conda environment or similar, and just install python related packages and avoid low level installations.

Do you know if this is possible? Are there any alternatives?

Thanks

**Comment by rodrigo-castellon** [comment]
Hi,
As a heads up, you’re actually referring to a Dockerfile that does not correspond to `representations_jukebox`. The one you’re looking for is https://github.com/p-lambda/jukemir/blob/main/representations/jukebox.dockerfile. That one matches up with the image layers as seen in https://hub.docker.com/layers/jukemir/representations_jukebox/latest/images/sha256-c87a4ee638680f7dd5a5306d71dfe65d8401b15eb80fd68655063821b17d7d45?context=explore.

Feel free to replicate with your own conda environment!

**Comment by rfalcon100** [comment]
Thanks for the update. I was able to locate the right the correct docker files.
It seems to be working ok now.
