### ISSUE TITLE
RuntimeError: Failed to initialize NCCL

### ISSUE THREAD

**Issue by KevinGoodman** [p-lambda/jukemir#8]
![image](https://user-images.githubusercontent.com/43786278/207263303-a2179415-63bf-4e39-877e-cd12ba048f40.png)
Thanks for sharing the code.
In the provided colab, I got this error in model setup, can anyone help please?@rodrigo-castellon 

I'm using CUDA 11.1 on RTX3090, and the pytorch version is 1.12.1

**Comment by suremangood** [comment]
I've also encountered this problem, does anyone have any advice?
